steps:

- id: Application Image Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/pythondemo_slurm-gcp:latest',
         ]

images: ['gcr.io/${PROJECT_ID}/pythondemo_slurm-gcp:latest']

